### ISSUE TITLE
[HW] BHASKAR PAL

### ISSUE THREAD

**Issue by pal-bhaskar** [datastaxdevs/workshop-intro-quarkus-cassandra#10]
**Name:** BHASKAR PAL
**Email:** bhaskarpaal@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bhaskar-pal-3364758a

Attach the homework screenshot below:
-----------------------------------------
![Screenshot 2021-10-28 at 6 24 03 PM](https://user-images.githubusercontent.com/69039695/139261409-b173abc4-a15d-4eec-a7b9-32503f0009e8.png)
![Screenshot 2021-10-28 at 6 21 52 PM](https://user-images.githubusercontent.com/69039695/139261443-90581a93-f186-4aad-945b-9798a5462f3a.png)
![Screenshot 2021-10-28 at 6 19 55 PM](https://user-images.githubusercontent.com/69039695/139261447-029884a7-8c3b-4259-bdd5-fe8380bddac5.png)
![Screenshot 2021-10-28 at 6 15 50 PM](https://user-images.githubusercontent.com/69039695/139261451-d30432f2-addb-4cd6-a642-8136355ba8c2.png)
![Screenshot 2021-10-28 at 6 14 51 PM](https://user-images.githubusercontent.com/69039695/139261452-2504b985-f8f0-4bfb-8675-27ccb52cfdbd.png)
![Screenshot 2021-10-28 at 5 58 03 PM](https://user-images.githubusercontent.com/69039695/139261458-d2d484b0-ad13-497d-80ef-19a6295ef5b3.png)
![Screenshot 2021-10-28 at 5 57 14 PM](https://user-images.githubusercontent.com/69039695/139261461-2016c1c0-3c87-496e-908e-0b20907edd19.png)

**Comment by ragsns** [comment]
Let me know if you did the debugging section as well and the packaging? Screen shots will be great if possible.

**Comment by pal-bhaskar** [comment]
Hello @ragsns ,
I have completed debugging section as well. Perhaps I missed to keep a screenshot.
Deploying to kubernetes - this step I was unable to complete, as I was unable run "kubectl" command-- it was not recognized by terminal. I have to work on this. Having said that, if you could bestow the badge upon me with this submission that'd be great. I look forward to future sessions from Datastax.
Thanks.

**Comment by ragsns** [comment]
You'll have to use a Kubernetes cluster. I've updated the original instructions to use okteto. Give it a shot when you can but thanks for trying!

**Comment by pal-bhaskar** [comment]
Thank you @ragsns . I'll definitely give it a shot.

I'm not seeing the badge issued in Badgr. Could you please help on this.

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay! Please LMK if still running into issues.

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# BHASKAR PAL

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/0ZiKXqOuQwyVv4o4ss6yqA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>

**Comment by pal-bhaskar** [comment]
Thanks a lot @ragsns and @HadesArchitect .
Looking forward to attend more sessions.
