### ISSUE TITLE
[HW] <Bertold Kral>

### ISSUE THREAD

**Issue by brollyka** [datastaxdevs/workshop-intro-quarkus-cassandra#11]
**Name:** Bertold Kral
**Email:** brollyka@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/brollyka/

Attach the homework screenshot below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/57646560/139339756-3677eb85-1b60-4e0e-a232-17cc1a4dfe72.png)
![image](https://user-images.githubusercontent.com/57646560/139340088-64ccd02c-c7f6-48aa-b11e-18ef58a65b09.png)
![image](https://user-images.githubusercontent.com/57646560/139341738-014e816b-6621-4179-8cd6-4acc74830a1c.png)

**Comment by ragsns** [comment]
Great effort. Can you please try to deploy to Kubernetes?
