### ISSUE TITLE
[HW] Workshop Intro to Quarkus and Cassandra by Joshua Turner

### ISSUE THREAD

**Issue by joshmanifold** [datastaxdevs/workshop-intro-quarkus-cassandra#12]
**Name:** Joshua Turner
**Email:** josh.turner@digintent.com
**Linkedin Profile:** https://www.linkedin.com/in/taztech/

I did all the lab work as shown below, but the Kubernetes step wasn't exactly clear. I realize it has something to do with the manifest and deploying from the command line with the "kubectl" command. It's on my training plan, so I'll likely have an aha moment any day now. So if you can provide further instruction on what's needed there or bestow the badge upon me with this submittal that'd be great. I look forward to future sessions, thanks.

Here's the contents of the "kubernetes.yml" file from Gitpod:

apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 6a11ec041cba544cc7c6219eb8a34c453aaf0106
    app.quarkus.io/build-timestamp: 2021-10-28 - 21:41:07 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: quarkus-cassandra
    app.kubernetes.io/version: "0.01"
  name: quarkus-cassandra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-cassandra
    app.kubernetes.io/version: "0.01"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 6a11ec041cba544cc7c6219eb8a34c453aaf0106
    app.quarkus.io/build-timestamp: 2021-10-28 - 21:41:07 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: quarkus-cassandra
    app.kubernetes.io/version: "0.01"
  name: quarkus-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-cassandra
      app.kubernetes.io/version: "0.01"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 6a11ec041cba544cc7c6219eb8a34c453aaf0106
        app.quarkus.io/build-timestamp: 2021-10-28 - 21:41:07 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: quarkus-cassandra
        app.kubernetes.io/version: "0.01"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/gitpod/quarkus-cassandra:0.01
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: quarkus-cassandra
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/86366869/139362077-1baae593-0e0c-43fa-b1bc-f7365c3a36da.png)

![image](https://user-images.githubusercontent.com/86366869/139362606-5f3558e0-d497-4c9c-9880-7f9f0ee8ea3b.png)

![image](https://user-images.githubusercontent.com/86366869/139361319-4772695f-6ca1-4c8b-b509-99ab25e79711.png)

![image](https://user-images.githubusercontent.com/86366869/139361999-0f7d44a8-ead5-46c8-abff-4da299aec2f1.png)

**Comment by ragsns** [comment]
Congrats, keep up the good work!

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay!

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# http

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/VDzh9TM_RhOkqZg9mFkl_w

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
