### ISSUE TITLE
[HW]  Vyom Rastogi 

### ISSUE THREAD

**Issue by vyomrastogi** [datastaxdevs/workshop-intro-quarkus-cassandra#13]
**Name:** Vyom Rastogi
**Email:** vyom.reloaded@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vyomrastogi/

I had to add 'quarkus-minikube' dependency to be able to generate a NodePort spec, as the default generated one expected a LoadBalancer service to be available. But, What a cool utility , made deployment so much more simpler and easier to learn !!!

Attach the homework screenshot below:
-----------------------------------------

**dockerhub image** - Task 10(d) and 10(e)

![quarkus-hw-2](https://user-images.githubusercontent.com/33644750/139611932-9af1b21b-1654-438f-9dd1-c3c3125b298d.png)

**deploy to kubernetes cluster (minikube)** - homework task

![quarkus-hw-1](https://user-images.githubusercontent.com/33644750/139611934-8f5d812a-9b04-47d4-b92d-aaabe3eb430b.png)

**Comment by ragsns** [comment]
Congratulations!

**Comment by vyomrastogi** [comment]
@ragsns how can we get the badge for this workshop?

**Comment by ragsns** [comment]
You need to go to badgr and use your email address. LMK if this does not work for you?

**Comment by vyomrastogi** [comment]
> You need to go to badgr and use your email address. LMK if this does not work for you?

It doesn't seemed to have worked. I couldn't see any badges in badgr after logging in. (I just created the account for first time)

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay! Please LMK if still facing issues?

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Vyom Rastogi

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/4nCyKwyJRpKRXtsBTu2-IA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
