### ISSUE TITLE
[HomeWork] Reactive Apps with Quarkus + Responsive Data with Cassandra

### ISSUE THREAD

**Issue by annasmbr** [datastaxdevs/workshop-intro-quarkus-cassandra#16]
**Name:** Anna Smirnova Berezina
**Email:** donanna77@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anna-smirnova-berezina
![DSC_0592](https://user-images.githubusercontent.com/66465655/140400228-a37a2d53-5a36-4ad1-8c9a-e588c88fb4ab.JPG)
![DSC_0593](https://user-images.githubusercontent.com/66465655/140400267-e3ece6b7-77f8-45c4-90c6-c9a6cd114d6a.JPG)

Attach the homework screenshot below:
-----------------------------------------

<SCREENSHOT>

**Comment by ragsns** [comment]
Can you confirm if you were able to deploy the app on a k8s cluster?

**Comment by annasmbr** [comment]
Yes

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay!

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Anna Smirnova Berezina

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/E1EejoZBQ6qP3rFEbDKjgA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
