### ISSUE TITLE
[HW] Steven Matison

### ISSUE THREAD

**Issue by ds-steven-matison** [datastaxdevs/workshop-intro-quarkus-cassandra#18]
**Name:** Steven Matison
**Email:** steven.matison@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/steven-matison/

Attach the homework screenshot below:
-----------------------------------------

![Screen Shot 2021-11-17 at 9 15 30 AM](https://user-images.githubusercontent.com/70520951/142217510-32387c98-3529-4a30-80f6-0e78fca6bcf0.png)
![Screen Shot 2021-11-17 at 9 15 08 AM](https://user-images.githubusercontent.com/70520951/142217513-fa9417e9-2f4a-4300-9f4c-e43ebf8ec85c.png)
![Screen Shot 2021-11-17 at 9 15 22 AM](https://user-images.githubusercontent.com/70520951/142217517-89e10106-5859-4df1-b556-0a3ef4cbbae3.png)

Feedback:

I still am unable to use gitpod.  The IDE just never loads, browser shows console has errors Mac + Chrome.   So I take Option B and i build myself and had issues with quickstart [pom.xml](https://github.com/datastax/cassandra-quarkus/blob/main/quickstart/pom.xml).  The version 1.1.2-SNAPSHOT does not exist i had to run with 1.1.1

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Steven Matison

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/c6r67Oc_QTmPOdIuXw7SGA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>

**Comment by ragsns** [comment]
Looks great! Keep up the good work!!
