### ISSUE TITLE
[HW] Vemal K.S

### ISSUE THREAD

**Issue by Vemal587** [datastaxdevs/workshop-intro-quarkus-cassandra#19]
Name: Vemal K.S
Email: vemal587@yahoo.com
Linkedin Profile: https://www.linkedin.com/in/vemal-k-s-106746113

Attach the homework screenshot below:
-----------------------------------------

**Create an Astra DB:**

![Screenshot (136)](https://user-images.githubusercontent.com/85180620/142826950-fcb02ba1-fe90-460b-82e6-589c6c0ef3a0.png)

**To-Do Application with modified text:**
![Screenshot (165)](https://user-images.githubusercontent.com/85180620/142828187-5e37f2b4-847f-436d-a666-e46abed3426a.png)

**Docker Image Deployment using my Username:**

![Screenshot (158)](https://user-images.githubusercontent.com/85180620/142827132-894fef03-fbdc-40d0-a20a-c0fa0f0300e2.png)

![Screenshot (156)](https://user-images.githubusercontent.com/85180620/142827193-9ebeaac9-7deb-4283-aac2-1b342a5d17d3.png)

**Adding a Kubernate Cluster in Okteto Cloud:**

![Screenshot (153)](https://user-images.githubusercontent.com/85180620/142827299-d65b2dc7-c297-4723-ba46-e70d0be3a842.png)

![Screenshot (155)](https://user-images.githubusercontent.com/85180620/142827378-378d0001-bded-4b44-a491-77f8ce696b4d.png)

**Deleting a Kubernate Cluster in Okteto Cloud:**

![Screenshot (160)](https://user-images.githubusercontent.com/85180620/142827716-4363c3c7-323b-4e3f-85c0-5aa002f6955d.png)

![Screenshot (164)](https://user-images.githubusercontent.com/85180620/142827987-bbb05894-3d79-4b6a-a2cb-7a81b4e016b9.png)

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Vemal K.S

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/HQ8yvVeqRiWZh9vowIlPXA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
