### ISSUE TITLE
[HW] Jean Pierre

### ISSUE THREAD

**Issue by Phawaq** [datastaxdevs/workshop-intro-quarkus-cassandra#2]
**Name:** Jean Pierre
**Email:** jprp82@gmail.com
**Linkedin Profile:** --

Attach the homework screenshot below:
-----------------------------------------

### Task 1 to 5
![AstraTodos](https://user-images.githubusercontent.com/9798940/139098936-6d3e189b-eace-443a-a7c4-81f9df1d64f8.JPG)

### Task 6
![test](https://user-images.githubusercontent.com/9798940/139099397-3da3c08e-33f1-47d3-a071-31d62fc64492.JPG)  

### Task 7  
![AstraTodos2](https://user-images.githubusercontent.com/9798940/139099876-fc0051da-61db-4d95-b11c-7a4c94b78a9b.JPG)

![AstraTodos3](https://user-images.githubusercontent.com/9798940/139100027-54c6d7c4-2ef4-4bfd-96d9-9c3924d53f39.JPG)

### Task 8  
![debug1](https://user-images.githubusercontent.com/9798940/139100192-45d76ef4-c738-411a-9d5c-77da2284569d.JPG)

### Task 9
![package](https://user-images.githubusercontent.com/9798940/139101272-06ae2133-e2eb-4093-a1cb-06af3b0bba11.JPG)

### Task 10
![targetYml](https://user-images.githubusercontent.com/9798940/139101774-16e10ffe-eae7-4900-a4f5-d7b2ce622ee2.JPG)

### Task 11
![runNativeImage](https://user-images.githubusercontent.com/9798940/139101896-71e1558c-a461-423d-9a3b-18f75575cfa1.JPG)
![runNativeImage2](https://user-images.githubusercontent.com/9798940/139101921-6ac686a8-d34f-4c8f-8dd6-96062e3a29f8.JPG)

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Jean Pierre

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/ReA4Hv6ZTr-g5Pj1x1T-rQ

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay!
