### ISSUE TITLE
[HW] Sarah Julia Kriesch 

### ISSUE THREAD

**Issue by skriesch** [datastaxdevs/workshop-intro-quarkus-cassandra#3]
**Name:** Sarah Julia Kriesch
**Email:** sarah-julia.kriesch@gmx.de
**Linkedin Profile:** https://www.linkedin.com/in/sarah-julia-kriesch/

Attach the homework screenshot below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/9654598/139109543-bd6268c5-4c77-4d39-b57f-c5b67cdb2a1b.png)
![image](https://user-images.githubusercontent.com/9654598/139109591-43b1f973-1263-4214-a33d-449bf58ce82a.png)

![image](https://user-images.githubusercontent.com/9654598/139110195-d7a71006-5fdb-4880-ab3a-f7f055f894d4.png)

**Comment by ragsns** [comment]
Can u clarify if u tried the other steps as well?
