### ISSUE TITLE
[HW] NEERAJ

### ISSUE THREAD

**Issue by aneeraj** [datastaxdevs/workshop-intro-quarkus-cassandra#4]
**Name:** Neeraj Ajithkumar
**Email:** neerajajithkumar@outlook.com
**Linkedin Profile:** https://www.linkedin.com/in/aneeraj/

Attach the homework screenshot below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/24623347/139110941-e6b58813-bc48-4028-b71c-ec284bbb296b.png)

![image](https://user-images.githubusercontent.com/24623347/139114560-20a13811-6db7-43fc-8820-d77614bc22ca.png)

![image](https://user-images.githubusercontent.com/24623347/139114639-a233b542-f3cc-454f-bfe0-39b37f6ed43d.png)

**Comment by aneeraj** [comment]
Hey @ragsns 

I do not see any badges assigned on Badgr. Will you be able to help here?

Regards
Neeraj

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Neeraj Ajithkumar

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/_aU7vOvPTJ-VtdKdehzGYQ

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>

**Comment by ragsns** [comment]
We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay! Please LMK if still running into issues?

**Comment by aneeraj** [comment]
> 
> 
> We had a bit of a glitch with the automation. Congrats for the effort and apologies for the delay! Please LMK if still running into issues?

Thanks @ragsns. All good now, Can see the badge. Thanks for the workshop again!
