### ISSUE TITLE
[HW] Ray Wu

### ISSUE THREAD

**Issue by bluraywu** [datastaxdevs/workshop-intro-quarkus-cassandra#5]
**Name:** Ray Wu
**Email:** wu013003@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ray-w-b77767167/
Attach the homework screenshot below:
-----------------------------------------
<img width="1423" alt="Screenshot 2021-10-27 at 18 13 07" src="https://user-images.githubusercontent.com/52205585/139114100-22f55486-2820-4106-9606-458a5e389620.png">
<img width="1361" alt="Screenshot 2021-10-27 at 18 15 36" src="https://user-images.githubusercontent.com/52205585/139114422-db84d56d-a396-4612-be6c-e4d3849348b3.png">

**Comment by ragsns** [comment]
Will need to see more steps or deployment into a K8S cluster.
