### ISSUE TITLE
[HW] <Rodrigo>

### ISSUE THREAD

**Issue by digaogt** [datastaxdevs/workshop-intro-quarkus-cassandra#6]
**Name:** Rodrigo Goncalves Torres
**Email:** rodrigogoncalvestorres9@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rodrigo-goncalves-torres/

Attach the homework screenshot below:
-----------------------------------------

![Screenshot 2021-10-27 142559](https://user-images.githubusercontent.com/39018881/139116265-e15a79e1-dd0a-48cb-9e5f-389dd03a8d43.jpg)

**Comment by ragsns** [comment]
Need to see more steps or deployment into a K8S cluster.

**Comment by digaogt** [comment]
![1](https://user-images.githubusercontent.com/39018881/140011350-41bee48f-145f-4d79-9174-01baf8c9a39b.jpg)
