### ISSUE TITLE
[HW] HICHAM

### ISSUE THREAD

**Issue by Hfasly** [datastaxdevs/workshop-intro-quarkus-cassandra#7]
Name: Hicham FASLY
Email: hicham.fasly@outlook.com
Linkedin Profile: https://www.linkedin.com/in/hicham-fasly-ba34bb44/

![Screen 1](https://user-images.githubusercontent.com/92569796/139120573-b19b388d-f25f-4536-a1b4-40cafc5f58cf.png)
![Screen 2](https://user-images.githubusercontent.com/92569796/139120588-1e6dab95-9083-4d0f-84f1-16c297c6aa06.png)

**Comment by ragsns** [comment]
Like to see more sections being tried (including packaging, debugging, etc.) or deployment into a K8S cluster.
