### ISSUE TITLE
[HW] <Rahul Bhojak>

### ISSUE THREAD

**Issue by Rahulbhojak** [datastaxdevs/workshop-intro-quarkus-cassandra#8]
**Name:** Rahul Bhojak
**Email:** rahulbhojak@gmail.com
**Linkedin Profile:** linkedin.com/in/rahulbhojak

Attach the homework screenshot below:
-----------------------------------------

<SCREENSHOT>

OPTION 1

10 D
![10 d docker login](https://user-images.githubusercontent.com/87692451/139133633-d0735e37-4642-4ccc-9673-00b958834baf.png)

10 E
![step 10e](https://user-images.githubusercontent.com/87692451/139133732-7391a2e7-0313-4103-b943-c89057d03052.png)

Some more today homework screen

![Screenshot_25](https://user-images.githubusercontent.com/87692451/139135438-1d601822-f39a-43d4-b8d6-123e46098a75.png)

![step 11 baa](https://user-images.githubusercontent.com/87692451/139136137-6dfa49fe-ecf7-4350-b94a-7533dc4cdcca.png)

![step 11 a](https://user-images.githubusercontent.com/87692451/139136229-e4357797-4cdd-44f9-a4a8-98abac1a2ffb.png)

**Comment by ragsns** [comment]
Can u clarify if u completed the debugging and packaging as well OR deployed into a K8S cluster?

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Rahul Bhojak

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/261SqCEHSiiOBRT-Q8ZufA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
