### ISSUE TITLE
[HW] <Khaja Moinuddin Mohammed>

### ISSUE THREAD

**Issue by moinuddin14** [datastaxdevs/workshop-intro-quarkus-cassandra#9]
**Name:** Khaja Moinuddin Mohammed
**Email:** moinuddinbtech@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/khaja143/

Attach the homework screenshot below:
-----------------------------------------

<img width="1680" alt="cassandra-quarkus-1" src="https://user-images.githubusercontent.com/1734908/139174874-03981c23-8a18-4fda-a632-864fea825220.png">
<img width="1680" alt="cassandra-quarkus-2" src="https://user-images.githubusercontent.com/1734908/139174881-e5f183ed-1cd7-47a5-b722-eb0f3d0348c6.png">
<img width="1680" alt="cassandra-quarkus-3" src="https://user-images.githubusercontent.com/1734908/139174885-879577c2-4406-4f51-a212-0a6dada0bfe6.png">

**Comment by ragsns** [comment]
Can you deploy into a k8s cluster?
